version: '3'

tasks:
  default:
    deps:
      - build

  build:
    desc: Build the fin binary
    cmds:
      - go build -o fin .

  install:
    desc: Build and install fin to $GOPATH/bin
    cmds:
      - CGO_ENABLED=0 go install -ldflags '-s -w' .
      - upx $GOPATH/bin/fin || echo Install upx for smaller binaries.

  test:
    desc: Run unit tests
    cmds:
      - go test -v ./...

  clean:
    desc: Remove built binary
    cmds:
      - rm -f fin
