# https://taskfile.dev

version: '3'

shopt: [globstar]

vars:
  TAG_CURRENT:
    sh: go tool svu current
  TAG_NEXT:
    sh: go tool svu next

tasks:
  default:
    - task: test
    - task: vuln
    - task: fmt
    - task: lint

  fmt: go tool gofumpt -w .
  test:
    - task: test:unit

  test:integration:
    cmd: go test -tags integration,{{.ARCHLINUX_TAG}} ./...
    vars:
      ARCHLINUX_TAG:
        sh: grep ID=arch /etc/os-release >/dev/null && echo archlinux || echo ''

  test:unit: go test ./...
  test:unit-gotestsum: go tool gotestsum
  vuln: go tool govulncheck ./...

  lint:
    - task: lint:editorconfig
    - task: lint:check-links

  lint:editorconfig: go tool editorconfig-checker

  lint:check-links: fd -0 .md | grep -v localhost | xargs -0 go tool xurls -fix

  tag:
    desc: Add next semver git tag
    cmds:
      - git tag -a -m {{.TAG_NEXT}} {{.TAG_NEXT}}
    status:
      - test {{.TAG_NEXT}} = {{.TAG_CURRENT}}

  tag:push:
    desc: Push git tags
    deps: [tag]
    cmds:
      - git push --tags
