# https://taskfile.dev

version: '3'

shopt: [globstar]

tasks:
  default:
    - task: test
    - task: vuln
    - task: fmt
    - task: lint:editorconfig
    - task: vendor

  fmt: go tool gofumpt -w .
  test: go test ./...
  test:gotestsum: go tool gotestsum
  vuln: go tool govulncheck ./...
  lint:editorconfig: go tool editorconfig-checker
  vendor: go mod vendor
