# https://taskfile.dev

version: '3'

shopt: [globstar]

vars:
  TAG_CURRENT:
    sh: go tool svu current
  TAG_NEXT:
    sh: go tool svu next

tasks:
  default: [{task: githook:pre-commit}]
  ai: go run github.com/charmbracelet/crush@latest
  githook:pre-commit: go tool lefthook run pre-commit --all-files
  githook:pre-push: go tool lefthook run pre-push --all-files
  test: go test work
  clean: rm -rf bin

  lint:check-links:
    cmd: go tool xurls **/*.md | grep -Ev '{{.EXCLUDE}}' | sort -u | go tool xurls -fix >/dev/null
    vars:
      EXCLUDE: localhost|twitter|9p.io|cluster.local
  lint:golangci-lint: go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.1 run

  tag:
    desc: Add next semver git tag
    cmds:
      - git tag -a -m {{.TAG_NEXT}} {{.TAG_NEXT}}
    status:
      - test {{.TAG_NEXT}} = {{.TAG_CURRENT}}

  tag:push:
    desc: Push git tags
    deps: [tag]
    cmds:
      - git push --tags
