# https://taskfile.dev

version: '3'

shopt: [globstar]

env:
  GOTOOLCHAIN: go1.26.0

vars:
  GO:
    sh: 'which go'
  TAG_CURRENT:
    sh: 'go tool svu current'
  TAG_NEXT:
    sh: 'go tool svu next'

tasks:
  default: [{task: githook:pre-commit}]

  crush: CRUSH_NEW_UI=1 go run github.com/charmbracelet/crush@v0.36.0
  githook:pre-commit: go tool lefthook run pre-commit --all-files
  githook:pre-push: go tool lefthook run pre-push --all-files

  clean: rm -rf bin

  lint:check-links:
    cmd: go tool xurls **/*.md | grep -Ev '{{.EXCLUDE}}' | sort -u | go tool xurls -fix >/dev/null
    vars:
      EXCLUDE: localhost|twitter|9p.io|cluster.local
  lint:golangci-lint: go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.9.0 run --fix

  tag:
    desc: Add next semver git tag
    cmds:
      - git tag -a -m {{.TAG_NEXT}} {{.TAG_NEXT}}
    status:
      - test {{.TAG_NEXT}} = {{.TAG_CURRENT}}

  tag:push:
    desc: Push git tags
    deps: [tag]
    cmds:
      - git push --tags

  test:
    deps:
      - test:go-integration
      - test:go-tools

  test:go-integration: go test work -tags integration -cover

  test:go-tools:
    desc: Test go tools to ensure none are broken due to dependency updates.
    cmd: go build -o /dev/null tool
