# https://taskfile.dev

version: '3'

shopt: [globstar]

vars:
  TAG_CURRENT:
    sh: go tool svu current
  TAG_NEXT:
    sh: go tool svu next

tasks:
  default:
    - task: test
    - task: vuln
    - task: fmt
    - task: lint:editorconfig

  fmt: go tool gofumpt -w .
  test:
    - task: test:unit
  test:integration: go test -tags integration ./...
  test:unit: go test ./...
  test:unit-gotestsum: go tool gotestsum
  vuln: go tool govulncheck ./...
  lint:editorconfig: go tool editorconfig-checker

  go:mod-tidy: go mod tidy

  tag:
    desc: Add next semver git tag
    cmds:
      - git tag -a -m {{.TAG_NEXT}} {{.TAG_NEXT}}
    status:
      - test {{.TAG_NEXT}} = {{.TAG_CURRENT}}

  tag:push:
    desc: Push git tags
    deps: [tag]
    cmds:
      - git push --tags
