# https://taskfile.dev

version: '3'

shopt: [globstar]

vars:
  TAG_CURRENT:
    sh: go tool svu current
  TAG_NEXT:
    sh: go tool svu next

tasks:
  default:
    - task: test
    - task: vuln
    - task: fmt
    - task: lint

  fmt: go tool gofumpt -w .
  test:
    - task: test:unit

  test:integration:
    cmd: go test -tags integration,{{.ARCHLINUX_TAG}} work
    vars:
      ARCHLINUX_TAG:
        sh: grep ID=arch /etc/os-release >/dev/null && echo archlinux || echo ''

  test:unit: go test work
  test:unit-gotestsum: go tool gotestsum work
  vuln: go tool govulncheck work

  lint:
    - task: lint:editorconfig
    - task: lint:check-links

  lint:editorconfig: go tool editorconfig-checker
  lint:check-links: fd .md | xargs go tool xurls -fix
  lint:trivy: go run github.com/aquasecurity/trivy/cmd/trivy@v0.65.0 fs .
  lint:modernize: go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...

  tag:
    desc: Add next semver git tag
    cmds:
      - git tag -a -m {{.TAG_NEXT}} {{.TAG_NEXT}}
    status:
      - test {{.TAG_NEXT}} = {{.TAG_CURRENT}}

  tag:push:
    desc: Push git tags
    cmds:
      - git push --tags
