# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - benthos test 0*.yaml

  run:
    cmds:
    - for:
        - 01*
        - 02*
        - 03*
        - 04*
      cmd: benthos --log.level warn -c {{.ITEM}}
