# https://taskfile.dev

version: '3'

tasks:
  default: [{task: schema}]

  schema:
    cmd: >
      curl -sL https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json |
      sed -e 's/https:/http:/' -e 's/draft-07\/schema/draft-07\/schema#/' |
      cue import jsonschema: - -p main --outfile schema.cue
    status: test -f schema.cue

    clean: rm -f schema.cue
