FROM golang:1.26-alpine AS builder
RUN apk add --no-cache gcc musl-dev
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go tool templ generate && go build -o /app/{{.project_name}} .

FROM alpine:3.21
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/{{.project_name}} .
COPY internal/static ./internal/static
COPY config.yaml .
EXPOSE 8080
CMD ["./{{.project_name}}"]
