version: "3"

vars:
  BIN_DIR: bin
  BIN_NAME: pavona
  BIN_UPX_NAME: '{{.BIN_NAME}}-upx'
  BIN: '{{.BIN_DIR}}/{{.BIN_NAME}}'
  BIN_UPX: '{{.BIN_DIR}}/{{.BIN_UPX_NAME}}'
  BIN_INSTALLED: '{{env "GOPATH"}}/bin/{{.BIN_NAME}}'

tasks:
  default:
    deps:
      - build

  build:
    desc: Build the pavona CLI
    sources:
      - '**/*.go'
      - '**/go.*'
      - templates/**
    generates:
      - '{{.BIN}}'
    cmds:
      - go build -o "{{.BIN}}" .

  upx:
    desc: Compress built binary with upx
    deps: [build]
    sources:
      - '{{.BIN}}'
    generates:
      - '{{.BIN_UPX}}'
    cmd: upx {{.BIN}} -o {{.BIN_UPX}} --force-overwrite

  install:
    desc: Install pavona to GOBIN
    deps: [upx]
    sources:
      - '{{.BIN_UPX}}'
    generates:
      - '{{.BIN_INSTALLED}}'
    cmd: cp {{.BIN_UPX}} {{.BIN_INSTALLED}}

  uninstall: rm -f {{.BIN_INSTALLED}}

  test:
    desc: Run all tests (unit + godog BDD scenarios)
    cmds:
      - go test ./...

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}

  open:docs:
    desc: Open package docs on pkg.go.dev.
    cmd: xdg-open https://pkg.go.dev/github.com/qjcg/arcadia/exp/pavona
