version: '3'

tasks:
  default:
    deps:
      - spec
      - letter
      - diploma

  spec:
    desc: Compile example spec to PDF
    sources:
      - spec-example.typ
    generates:
      - spec-example.pdf
    cmds:
      - typst compile spec-example.typ

  letter:
    desc: Compile example letter to PDF
    sources:
      - letter-example.typ
    generates:
      - letter-example.pdf
    cmds:
      - typst compile letter-example.typ

  diploma:
    desc: Compile diploma to PDF
    sources:
      - diploma-example.typ
    generates:
      -  diploma-example.pdf
    cmds:
      - typst compile diploma-example.typ

  diploma:batch:
    desc: Compile a batch of diplomas
    cmds:
      - typst compile diploma-batch.typ

  diploma:input:
    desc: Compile a batch of diplomas
    cmds:
      - >
        typst compile diploma-input.typ diploma-input_fooman.pdf
        --input student=FooMan
        --input course='Plan9 for Dummies'
        --input instructor='Rob Pike'
        --input dates='Feb 16-18, 2026'
      - >
        typst compile diploma-input.typ diploma-input_barman.pdf
        --input student=BarMan
        --input course='Plan9 for Dummies'
        --input instructor='Rob Pike'
        --input dates='Feb 16-18, 2026'

  clean: rm -f *.pdf
