version: '3'

tasks:
  default:
    deps:
      - build

  build:
    desc: Build PDF files.
    sources:
      - '*-example.typ'
      - diploma-batch.typ
    generates:
      - '*.pdf'
    cmds:
      - for: sources
        cmd: typst compile {{.ITEM}}

  diploma:input:
    desc: Create diplomas based on CLI input values.
    sources:
      - diploma.typ
      - diploma-input.typ
    generates:
      - diploma-input_*.pdf
    cmds:
      - for: [fooman, barman, bazman]
        cmd: >
          typst compile diploma-input.typ diploma-input_{{.ITEM}}.pdf
          --input student={{.ITEM}}
          --input course='Plan9 for Dummies'
          --input instructor='Rob Pike'
          --input dates='Feb 16-18, 2026'

  clean:
    desc: Remove PDF files.
    cmd: rm -f *.pdf
