# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

project_name: horeb

builds:
  - binary: horeb
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - go_first_class
    hooks:
      post:
        - test $(uname -s) != Darwin && upx "{{.Path}}"

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64_
      {{- else if eq .Arch "386" }}i386_
      {{- else }}{{ .Arch }}_{{ end }}
      {{- if .Arm }}v{{ .Arm }}_{{ end }}
      {{- .Version }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

dockers:
  - image_templates:
      - qjcg/horeb:{{ .Version }}
      - qjcg/horeb:latest

nfpms:
  - maintainer: ${NFPM_MAINTAINER}
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - archlinux

changelog:

  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
