# https://taskfile.dev

version: '3'

vars:
  CONFIG: config.yaml
  WS_ADDR: localhost:4195
  WS_PATH: /ws
  WS_URL: ws://{{.WS_ADDR}}{{.WS_PATH}}

tasks:
  default:
    cmds:
      - task: test
      - task: clean
      - task: serve

  serve:
    desc: Run benthos listening for websocket input.
    cmds:
      - go tool bento -c {{.CONFIG}}

  test:
    desc: Test benthos websocket server via websocat.
    cmds:
      - websocat {{.WS_URL}}

  clean:
    desc: Use killall to halt all running benthos processes.
    cmds:
      - killall bento || true
