version: '3'

tasks:
  default:
    deps:
      - test

  build:
    desc: Build the sv binary
    sources:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    generates:
      - sv
    cmds:
      - go build -o sv ./cmd/sv/main.go

  install:
    desc: Install the sv binary
    deps: [build]
    cmds:
      - go install ./cmd/sv/main.go

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f sv
