# https://taskfile.dev

version: '3'

vars:
  TEST_STRING: foo

tasks:
  default:
    aliases: [test]
    cmds:
      - task: test_no_config
      - task: test_empty_config

  test_no_config:
    cmds:
      - echo {{.TEST_STRING}} | go tool bento | grep {{.TEST_STRING}}

  test_empty_config:
    cmds:
      - echo {{.TEST_STRING}} | go tool bento --chilled -c config.yaml | grep {{.TEST_STRING}}
