# https://taskfile.dev

version: '3'

vars:
  CONFIG: config.yaml

tasks:
  default:
    aliases: [test]
    cmds:
      - benthos test {{.CONFIG}}

  run:
    cmds:
      - benthos -c {{.CONFIG}}

  run-streams:
    cmds:
      - benthos -c config.yaml streams {client,server}.yaml
