// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"
)

type Card struct {
	ID        string
	Type      string
	ModuleID  string
	Front     string
	Back      string
	Metadata  sql.NullString
	CreatedAt string
	UpdatedAt string
}

type Module struct {
	ID          string
	Title       string
	Description sql.NullString
	Category    sql.NullString
	CreatedAt   string
	UpdatedAt   string
}

type Review struct {
	ID           string
	CardID       string
	SessionID    sql.NullString
	Quality      int64
	IntervalDays int64
	EaseFactor   float64
	ReviewCount  int64
	NextReviewAt string
	ReviewedAt   string
}

type Session struct {
	ID        string
	ModuleID  string
	Mode      string
	StartedAt string
	EndedAt   sql.NullString
}
