// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package storage

import (
	"context"
	"database/sql"
)

const countCardsByModule = `-- name: CountCardsByModule :one
SELECT COUNT(*) as count
FROM cards
WHERE module_id = ?
`

func (q *Queries) CountCardsByModule(ctx context.Context, moduleID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardsByModule, moduleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCardsDueForReview = `-- name: CountCardsDueForReview :one
SELECT COUNT(*) as count
FROM cards c
LEFT JOIN reviews r ON c.id = r.card_id
WHERE r.next_review_at IS NULL OR r.next_review_at <= ?
`

func (q *Queries) CountCardsDueForReview(ctx context.Context, nextReviewAt string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardsDueForReview, nextReviewAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCardsDueForReviewByModule = `-- name: CountCardsDueForReviewByModule :one
SELECT COUNT(*) as count
FROM cards c
LEFT JOIN reviews r ON c.id = r.card_id
WHERE c.module_id = ?
AND (r.next_review_at IS NULL OR r.next_review_at <= ?)
`

type CountCardsDueForReviewByModuleParams struct {
	ModuleID     string
	NextReviewAt string
}

func (q *Queries) CountCardsDueForReviewByModule(ctx context.Context, arg CountCardsDueForReviewByModuleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardsDueForReviewByModule, arg.ModuleID, arg.NextReviewAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviews = `-- name: CountReviews :one
SELECT COUNT(*) as count
FROM reviews
`

func (q *Queries) CountReviews(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsByModule = `-- name: CountReviewsByModule :one
SELECT COUNT(*) as count
FROM reviews r
JOIN cards c ON r.card_id = c.id
WHERE c.module_id = ?
`

func (q *Queries) CountReviewsByModule(ctx context.Context, moduleID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviewsByModule, moduleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCard = `-- name: CreateCard :exec
INSERT INTO cards (id, type, module_id, front, back, metadata, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCardParams struct {
	ID        string
	Type      string
	ModuleID  string
	Front     string
	Back      string
	Metadata  sql.NullString
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) error {
	_, err := q.db.ExecContext(ctx, createCard,
		arg.ID,
		arg.Type,
		arg.ModuleID,
		arg.Front,
		arg.Back,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createModule = `-- name: CreateModule :exec
INSERT INTO modules (id, title, description, category, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateModuleParams struct {
	ID          string
	Title       string
	Description sql.NullString
	Category    sql.NullString
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) error {
	_, err := q.db.ExecContext(ctx, createModule,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createReview = `-- name: CreateReview :exec
INSERT INTO reviews (id, card_id, session_id, quality, interval_days, ease_factor, review_count, next_review_at, reviewed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateReviewParams struct {
	ID           string
	CardID       string
	SessionID    sql.NullString
	Quality      int64
	IntervalDays int64
	EaseFactor   float64
	ReviewCount  int64
	NextReviewAt string
	ReviewedAt   string
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) error {
	_, err := q.db.ExecContext(ctx, createReview,
		arg.ID,
		arg.CardID,
		arg.SessionID,
		arg.Quality,
		arg.IntervalDays,
		arg.EaseFactor,
		arg.ReviewCount,
		arg.NextReviewAt,
		arg.ReviewedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, module_id, mode, started_at, ended_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string
	ModuleID  string
	Mode      string
	StartedAt string
	EndedAt   sql.NullString
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.ModuleID,
		arg.Mode,
		arg.StartedAt,
		arg.EndedAt,
	)
	return err
}

const getAllModuleStats = `-- name: GetAllModuleStats :many
SELECT
  c.module_id,
  COUNT(DISTINCT c.id) as total_cards,
  COUNT(DISTINCT r.id) as reviewed_cards,
  COALESCE(AVG(r.quality), 0) as avg_quality
FROM cards c
LEFT JOIN reviews r ON c.id = r.card_id
GROUP BY c.module_id
`

type GetAllModuleStatsRow struct {
	ModuleID      string
	TotalCards    int64
	ReviewedCards int64
	AvgQuality    interface{}
}

func (q *Queries) GetAllModuleStats(ctx context.Context) ([]GetAllModuleStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllModuleStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllModuleStatsRow
	for rows.Next() {
		var i GetAllModuleStatsRow
		if err := rows.Scan(
			&i.ModuleID,
			&i.TotalCards,
			&i.ReviewedCards,
			&i.AvgQuality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCard = `-- name: GetCard :one
SELECT id, type, module_id, front, back, metadata, created_at, updated_at
FROM cards
WHERE id = ?
`

func (q *Queries) GetCard(ctx context.Context, id string) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCard, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ModuleID,
		&i.Front,
		&i.Back,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModule = `-- name: GetModule :one
SELECT id, title, description, category, created_at, updated_at
FROM modules
WHERE id = ?
`

func (q *Queries) GetModule(ctx context.Context, id string) (Module, error) {
	row := q.db.QueryRowContext(ctx, getModule, id)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModuleStats = `-- name: GetModuleStats :one
SELECT
  COUNT(DISTINCT c.id) as total_cards,
  COUNT(DISTINCT r.id) as reviewed_cards,
  COALESCE(AVG(r.quality), 0) as avg_quality
FROM cards c
LEFT JOIN reviews r ON c.id = r.card_id
WHERE c.module_id = ?
`

type GetModuleStatsRow struct {
	TotalCards    int64
	ReviewedCards int64
	AvgQuality    interface{}
}

func (q *Queries) GetModuleStats(ctx context.Context, moduleID string) (GetModuleStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getModuleStats, moduleID)
	var i GetModuleStatsRow
	err := row.Scan(&i.TotalCards, &i.ReviewedCards, &i.AvgQuality)
	return i, err
}

const getReviewDates = `-- name: GetReviewDates :many
SELECT reviewed_at
FROM reviews
ORDER BY reviewed_at DESC
`

func (q *Queries) GetReviewDates(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getReviewDates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var reviewed_at string
		if err := rows.Scan(&reviewed_at); err != nil {
			return nil, err
		}
		items = append(items, reviewed_at)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewForCard = `-- name: GetReviewForCard :one
SELECT id, card_id, session_id, quality, interval_days, ease_factor, review_count, next_review_at, reviewed_at
FROM reviews
WHERE card_id = ?
ORDER BY reviewed_at DESC
LIMIT 1
`

func (q *Queries) GetReviewForCard(ctx context.Context, cardID string) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewForCard, cardID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.SessionID,
		&i.Quality,
		&i.IntervalDays,
		&i.EaseFactor,
		&i.ReviewCount,
		&i.NextReviewAt,
		&i.ReviewedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, module_id, mode, started_at, ended_at
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Mode,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listCardsByModule = `-- name: ListCardsByModule :many
SELECT id, type, module_id, front, back, metadata, created_at, updated_at
FROM cards
WHERE module_id = ?
`

func (q *Queries) ListCardsByModule(ctx context.Context, moduleID string) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCardsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ModuleID,
			&i.Front,
			&i.Back,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsForReview = `-- name: ListCardsForReview :many
SELECT c.id, c.type, c.module_id, c.front, c.back, c.metadata, c.created_at, c.updated_at
FROM cards c
LEFT JOIN reviews r ON c.id = r.card_id
WHERE c.module_id = ?
AND (r.next_review_at IS NULL OR r.next_review_at <= ?)
ORDER BY COALESCE(r.next_review_at, '1970-01-01')
LIMIT ?
`

type ListCardsForReviewParams struct {
	ModuleID     string
	NextReviewAt string
	Limit        int64
}

func (q *Queries) ListCardsForReview(ctx context.Context, arg ListCardsForReviewParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCardsForReview, arg.ModuleID, arg.NextReviewAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ModuleID,
			&i.Front,
			&i.Back,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModules = `-- name: ListModules :many
SELECT id, title, description, category, created_at, updated_at
FROM modules
`

func (q *Queries) ListModules(ctx context.Context) ([]Module, error) {
	rows, err := q.db.QueryContext(ctx, listModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Module
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :exec
UPDATE reviews
SET quality = ?, interval_days = ?, ease_factor = ?, review_count = ?, next_review_at = ?, reviewed_at = ?
WHERE id = ?
`

type UpdateReviewParams struct {
	Quality      int64
	IntervalDays int64
	EaseFactor   float64
	ReviewCount  int64
	NextReviewAt string
	ReviewedAt   string
	ID           string
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) error {
	_, err := q.db.ExecContext(ctx, updateReview,
		arg.Quality,
		arg.IntervalDays,
		arg.EaseFactor,
		arg.ReviewCount,
		arg.NextReviewAt,
		arg.ReviewedAt,
		arg.ID,
	)
	return err
}
