version: '3'

vars:
  BIN_DIR: bin
  BIN: '{{.BIN_DIR}}/slidesdeck'

tasks:
  tools:
    desc: Install tools
    cmds:
      - go get -tool github.com/a-h/templ/cmd/templ
      - go get -tool github.com/air-verse/air
      - go get -tool github.com/evanw/esbuild/cmd/esbuild

  build:templ:
    desc: Generate templ components
    cmds:
      - go tool templ generate
    sources:
      - '**/*.templ'
      - '**/go.*'
      - '**/*.go'
    generates:
      - '**/*_templ.go'

  build:css:
    desc: Build CSS with Tailwind v4
    cmds:
      - go run scripts/split_themes.go
      - ./tailwindcss -i {{.IN}} -o {{.OUT}} --minify
    sources:
      - 'assets/src/**/*.css'
    generates:
      - '{{.OUT}}'
    vars:
      IN: assets/src/css/main.css
      OUT: assets/dist/main.css

  build:js:
    desc: Build JS with esbuild
    cmds:
    - go tool esbuild {{.IN}} --bundle --minify --external:worker_threads --outfile={{.OUT}}
    sources:
      - assets/src/js/**/*.js
    generates:
      - '{{.OUT}}'
    vars:
      IN: assets/src/js/main.js
      OUT: assets/dist/main.js

  build:
    desc: Build the project
    deps: [build:templ, build:css, build:js]
    cmds:
      - go build -o {{.BIN}} .
    sources:
      - '**/go.*'
      - '**/*.go'
      - 'assets/dist/**'
    generates:
      - '{{.BIN}}'

  demo:
    deps: [build]
    cmds:
      - '{{.BIN}} examples/overview.org'
      - xdg-open examples/overview.html
    sources:
      - examples/overview.org
    generates:
      - examples/overview.html

  clean: rm -rf {{.BIN}} assets/dist examples/*.html

  dev:
    desc: Run with hot reload
    cmds:
      - go tool air

  test:
    desc: Run tests
    cmds:
      - go tool gotestsum ./...
