version: '3'

vars:
  BIN_DIR: bin
  BIN: '{{.BIN_DIR}}/slidesdeck'
  BIN_INSTALLED: $GOBIN/slidesdeck

tasks:
  default:
    deps: [build]

  build:templ:
    desc: Generate templ components
    cmds:
      - go tool templ generate
    sources:
      - '**/*.templ'
      - '**/go.*'
      - '**/*.go'
    generates:
      - '**/*_templ.go'

  build:css-split-themes:
    desc: Split out the tailwind themes into individual modular CSS files.
    cmds:
      - go run scripts/split_themes.go
    sources:
      - scripts/split_themes.go
      - assets/src/css/vendor/themes.css
    generates:
      - assets/src/css/themes/*.css

  build:css:
    desc: Build CSS with Tailwind v4
    deps: [build:css-split-themes]
    cmds:
      - ./tailwindcss -i {{.IN}} -o {{.OUT}} --minify
    sources:
      - 'assets/src/**/*.css'
    generates:
      - '{{.OUT}}'
    vars:
      IN: assets/src/css/main.css
      OUT: assets/dist/main.css

  build:js:
    desc: Build JS with esbuild
    cmds:
    - go tool esbuild {{.IN}} --bundle --minify --external:worker_threads --outfile={{.OUT}}
    sources:
      - assets/src/js/**/*.js
    generates:
      - '{{.OUT}}'
    vars:
      IN: assets/src/js/main.js
      OUT: assets/dist/main.js

  build:
    desc: Build the project
    deps: [build:templ, build:css, build:js]
    cmds:
      - go build -o {{.BIN}} .
    sources:
      - '**/go.*'
      - '**/*.go'
      - 'assets/dist/**'
    generates:
      - '{{.BIN}}'

  install:
    desc: Install go binary
    deps: [build]
    cmds:
      - cp {{.BIN}} {{.BIN_INSTALLED}}
      - upx {{.BIN_INSTALLED}}
    sources:
      - '**/go.*'
      - '**/*.go'
      - 'assets/dist/**'
    generates:
      - '{{.BIN_INSTALLED}}'

  demo:
    deps: [build]
    cmds:
      - '{{.BIN}} examples/overview.org'
      - xdg-open examples/overview.html
    sources:
      - examples/overview.org
    generates:
      - examples/overview.html

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BIN}} assets/dist examples/*.html
      - mkdir -p assets/dist

  dev:
    desc: Run with hot reload
    cmds:
      - go tool air

  test:
    desc: Run tests
    cmds:
      - go tool gotestsum ./...
