# https://taskfile.dev

version: '3'

vars:
  CONFIG: config.yaml

tasks:
  default:
    - task: run

  run:
    cmds:
      - go tool bento -c {{.CONFIG}}

  run:streams:
    cmds:
      - go tool bento -c config.yaml streams {client,server}.yaml
