name: Release Modules
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v6
      with:
        go-version-file: go.work

    - name: Install sv
      run: CGO_ENABLED=0 go install -ldflags '-s -w' github.com/qjcg/arcadia/exp/sv@v0.8.2

    - name: Compute version bumps
      id: bumps
      run: |
        set -o pipefail
        CHANGES=$(sv next --all)
        TAGS=$(echo "$CHANGES" | grep -E '^(.*/)?v[0-9]+\.[0-9]+\.[0-9]+$' || true)
        if [[ -n "$TAGS" ]]; then
          printf 'tags<<EOF\n%s\nEOF\n' "$TAGS" >> $GITHUB_OUTPUT
        fi

    - name: Tag and Release
      if: steps.bumps.outputs.tags != ''
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        sv next --all --tag
        git push origin --tags

        while read tag; do
          gh release create "$tag" --generate-notes
        done <<< "${{ steps.bumps.outputs.tags }}"
