// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

import (
	"fmt"

	"github.com/charmbracelet/arcadia/x/slidesdeck/internal/parser"
)

func Layout(deck *parser.Deck, initialTheme string, css string, js string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" data-theme=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(initialTheme)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components.templ`, Line: 10, Col: 42}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(deck.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components.templ`, Line: 14, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw("<style type=\"text/css\">\n"+css+"\n</style>").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</head><body class=\"bg-base-100 text-base-content\" x-data=\"slideshow\"><div class=\"h-screen w-screen overflow-hidden relative\"><div class=\"slides-container h-full w-full\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for i, slide := range deck.Slides {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<section class=\"slide absolute inset-0 transition-opacity duration-300\" x-show=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("currentSlide == %d", i))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components.templ`, Line: 24, Col: 52}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" x-cloak><div class=\"max-w-4xl mx-auto\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.Raw(slide.Content).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div><div class=\"absolute bottom-4 right-4 text-sm opacity-50\"><span x-text=\"currentSlide + 1\"></span> / <span x-text=\"totalSlides\"></span></div><div class=\"absolute inset-0 bg-base-300/90 flex items-center justify-center z-50\" x-show=\"showHelp\" x-transition @click.self=\"showHelp = false\" x-cloak><div class=\"bg-base-100 p-8 rounded-2xl shadow-xl max-w-lg w-full\"><h2 class=\"text-3xl font-bold mb-4\">Slidesdeck Help</h2><div class=\"space-y-2\"><div class=\"flex justify-between\"><span>Next Slide</span><kbd class=\"kbd kbd-sm\">n</kbd> / <kbd class=\"kbd kbd-sm\">→</kbd></div><div class=\"flex justify-between\"><span>Previous Slide</span><kbd class=\"kbd kbd-sm\">p</kbd> / <kbd class=\"kbd kbd-sm\">←</kbd></div><div class=\"flex justify-between\"><span>First Slide</span><kbd class=\"kbd kbd-sm\">Shift</kbd>+<kbd class=\"kbd kbd-sm\">Alt</kbd>+<kbd class=\"kbd kbd-sm\">,</kbd></div><div class=\"flex justify-between\"><span>Last Slide</span><kbd class=\"kbd kbd-sm\">Shift</kbd>+<kbd class=\"kbd kbd-sm\">Alt</kbd>+<kbd class=\"kbd kbd-sm\">.</kbd></div><div class=\"flex justify-between\"><span>Fullscreen</span><kbd class=\"kbd kbd-sm\">f</kbd></div><div class=\"flex justify-between\"><span>Theme Palette</span><kbd class=\"kbd kbd-sm\">t</kbd></div><div class=\"flex justify-between\"><span>Search</span><kbd class=\"kbd kbd-sm\">/</kbd></div><div class=\"flex justify-between\"><span>Line Numbers</span><kbd class=\"kbd kbd-sm\">N</kbd></div><div class=\"flex justify-between\"><span>Pause Mode</span><kbd class=\"kbd kbd-sm\">Shift</kbd>+<kbd class=\"kbd kbd-sm\">P</kbd></div><div class=\"flex justify-between\"><span>Toggle Help</span><kbd class=\"kbd kbd-sm\">?</kbd></div></div><div class=\"mt-6 text-center\"><button class=\"btn btn-primary\" @click=\"showHelp = false\">Close</button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ThemePalette().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = SearchPalette().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = PauseMode().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw("<script type=\"text/javascript\">\n"+js+"\n</script>").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ThemePalette() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<div class=\"absolute inset-0 bg-black/50 backdrop-blur-sm flex items-start justify-center pt-20 z-[60]\" x-show=\"showThemePalette\" @keydown.escape.window=\"showThemePalette = false\" x-cloak><div class=\"bg-base-100 rounded-lg shadow-2xl w-full max-w-md overflow-hidden\"><input type=\"text\" class=\"input input-ghost w-full focus:outline-none border-b border-base-300 rounded-none h-14\" placeholder=\"Search themes...\" x-ref=\"themeSearch\" @input=\"searchThemes($event.target.value)\"><div class=\"max-h-96 overflow-y-auto\"><template x-for=\"theme in filteredThemes\" :key=\"theme\"><div class=\"px-4 py-3 hover:bg-base-200 cursor-pointer flex justify-between items-center\" :class=\"currentTheme === theme ? 'bg-primary text-primary-content' : ''\" @click=\"setTheme(theme)\"><span x-text=\"(['dark', 'synthwave', 'halloween', 'forest', 'aqua', 'black', 'luxury', 'dracula', 'business', 'night', 'coffee', 'dim', 'sunset', 'abyss'].includes(theme) ? 'dark: ' : 'light: ') + theme\"></span> <span x-show=\"currentTheme === theme\">✓</span></div></template></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SearchPalette() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div class=\"absolute inset-0 bg-black/50 backdrop-blur-sm flex items-start justify-center pt-20 z-[60]\" x-show=\"showSearch\" @keydown.escape.window=\"showSearch = false\" x-cloak><div class=\"bg-base-100 rounded-lg shadow-2xl w-full max-w-2xl overflow-hidden\"><input type=\"text\" class=\"input input-ghost w-full focus:outline-none border-b border-base-300 rounded-none h-14 text-xl\" placeholder=\"Search slides...\" x-ref=\"slideSearch\" @input=\"performSearch($event.target.value)\"><div class=\"max-h-96 overflow-y-auto\"><template x-for=\"result in searchResults\" :key=\"result.id\"><div class=\"px-4 py-4 hover:bg-base-200 cursor-pointer border-b border-base-300 last:border-0\" @click=\"jumpToSlide(result.id)\"><h3 class=\"font-bold text-lg\" x-text=\"result.title\"></h3><p class=\"text-sm opacity-60\">Slide <span x-text=\"result.id + 1\"></span></p></div></template><div x-show=\"searchQuery && searchResults.length === 0\" class=\"p-8 text-center opacity-50\">No slides found matching \"<span x-text=\"searchQuery\"></span>\"</div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func PauseMode() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<div class=\"absolute inset-0 bg-base-100 flex flex-col items-center justify-center z-[100]\" x-show=\"showPause\" x-cloak><div class=\"text-center\"><h1 class=\"text-9xl font-black mb-8\" x-text=\"timeRemaining\">00:00</h1><p class=\"text-4xl opacity-70\" x-text=\"pauseMessage\"></p><div class=\"mt-12 flex gap-4 justify-center\" x-show=\"!timerRunning\"><input type=\"text\" class=\"input input-bordered text-lg w-64\" placeholder=\"Break message...\" x-model=\"pauseMessage\"> <input type=\"number\" class=\"input input-bordered text-lg w-24\" placeholder=\"Mins\" x-model=\"pauseMinutes\"> <button class=\"btn btn-primary btn-lg\" @click=\"startTimer()\">Start Break</button></div><div class=\"mt-8\" x-show=\"timerRunning\"><button class=\"btn btn-ghost\" @click=\"resetTimer()\">Reset</button></div><button class=\"btn btn-circle btn-outline absolute top-8 right-8\" @click=\"showPause = false\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M6 18L18 6M6 6l12 12\"></path></svg></button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
